### ISSUE TITLE
Change name of CleanUp.py file

### ISSUE THREAD

**Issue by arashsa** [apnorton/tsp-art#1]
This filename is incorrect. 

```import correct from cleanup``` returns an error message.

**Comment by apnorton** [comment]
Good catch; I'll get this fixed by the end of the week.

**Comment by apnorton** [comment]
...and my Linux install broke.  I haven't forgotten about this; it'll be a bit longer before I get to it, though.

**Comment by apnorton** [comment]
Finally got around to fixing my linux install; I changed `cleanup` to `CleanUp` in the TSPArt.py file.
